version: "3.9"

services:
  database:
    image: postgres
    container_name: database_agrotec
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=agrotec_admin
      - POSTGRES_PASSWORD=2365
      - POSTGRES_DB=agrotec
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_agrotec
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
